// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsPuWy5PVj143G2AWmk2CiucbpSf6ry0E',
    appId: '1:767709878070:web:eebeb196df4d8612330597',
    messagingSenderId: '767709878070',
    projectId: 'commerceapp-a1e33',
    authDomain: 'commerceapp-a1e33.firebaseapp.com',
    storageBucket: 'commerceapp-a1e33.appspot.com',
    measurementId: 'G-K4GZWR30SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC-Qtg5PEMQ9iYo1VKx9f4beieanLkUjw',
    appId: '1:767709878070:android:5a5c556747f9ed44330597',
    messagingSenderId: '767709878070',
    projectId: 'commerceapp-a1e33',
    storageBucket: 'commerceapp-a1e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2IS5XM3nMwI3RC90_jU8bcuBOIcwenw',
    appId: '1:767709878070:ios:92c783b09bdb84d2330597',
    messagingSenderId: '767709878070',
    projectId: 'commerceapp-a1e33',
    storageBucket: 'commerceapp-a1e33.appspot.com',
    iosBundleId: 'com.example.commerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE2IS5XM3nMwI3RC90_jU8bcuBOIcwenw',
    appId: '1:767709878070:ios:92c783b09bdb84d2330597',
    messagingSenderId: '767709878070',
    projectId: 'commerceapp-a1e33',
    storageBucket: 'commerceapp-a1e33.appspot.com',
    iosBundleId: 'com.example.commerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsPuWy5PVj143G2AWmk2CiucbpSf6ry0E',
    appId: '1:767709878070:web:a57481386a5d121c330597',
    messagingSenderId: '767709878070',
    projectId: 'commerceapp-a1e33',
    authDomain: 'commerceapp-a1e33.firebaseapp.com',
    storageBucket: 'commerceapp-a1e33.appspot.com',
    measurementId: 'G-17FWY7Z5PR',
  );
}
